### ISSUE TITLE
I want to use UUID as the primary key, but I'm having some problems

### ISSUE THREAD

**Issue by CameliaOo** [sqlobject/sqlobject#167]
from sqlobject import *

sqlhub.processConnection = "mysql://root:root@localhost:3306/gov_info"

class Text(SQLObject):
    class sqlmeta:
        idName = 'guid'
        idType = str

    name = StringCol()

Text(id='3F2F5F24-A0A1-4A13-98A2-0F2C7E857C1A', name='Jack')

**Comment by CameliaOo** [comment]
Traceback (most recent call last):
  File "C:\Users\Mason\PycharmProjects\pythonProject\gov-info\test.py", line 14, in <module>
    Text(id='3F2F5F24-A0A1-4A13-98A2-0F2C7E857C1A', name='sdfb')
  File "C:\Users\Mason\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlobject\main.py", line 1301, in __init__
    self._create(id, **kw)
  File "C:\Users\Mason\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlobject\main.py", line 1352, in _create
    self._SO_finishCreate(id)
  File "C:\Users\Mason\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlobject\main.py", line 1377, in _SO_finishCreate
    id = self._connection.queryInsertID(self,
AttributeError: 'str' object has no attribute 'queryInsertID'

**Comment by drnlm** [comment]
processConnection shouldn't be a string - you want 
```python
sqlhub.processConnection = connectionForURI("mysql://root:root@localhost:3306/gov_info")
```

See http://www.sqlobject.org/SQLObject.html#declaring-a-connection

Also, you'll need to create the table by calling
```python
Text.createTable()
```

before you can insert anything.

**Comment by CameliaOo** [comment]
Thanks
