### ISSUE TITLE
sqlobject dbconnection throwing attribute error in python 3.10

### ISSUE THREAD

**Issue by AstroFloof** [sqlobject/sqlobject#178]
```py
/media/gamedisk/PycharmProjects/FICSIT-Fred/lx310venv/bin/python /media/gamedisk/PycharmProjects/FICSIT-Fred/bot/bot.py
Traceback (most recent call last):
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/lx310venv/lib/python3.10/site-packages/sqlobject/dbconnection.py", line 992, in getConnection
    return self.threadingLocal.connection
AttributeError: '_thread._local' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/lx310venv/lib/python3.10/site-packages/sqlobject/dbconnection.py", line 995, in getConnection
    return self.processConnection
AttributeError: 'ConnectionHub' object has no attribute 'processConnection'. Did you mean: 'threadConnection'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/bot/bot.py", line 8, in <module>
    from cogs import commands, crashes, dialogflow, mediaonly, webhooklistener, welcome, levelling
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/bot/cogs/commands.py", line 8, in <module>
    from libraries import help as bot_help
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/bot/libraries/help.py", line 6, in <module>
    class Fred_Help_Embed(Embed):
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/bot/libraries/help.py", line 8, in Fred_Help_Embed
    help_colour = config.ActionColours.fetch("Light Blue")
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/bot/config.py", line 113, in fetch
    query = ActionColours.selectBy(name=name.lower())
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/lx310venv/lib/python3.10/site-packages/sqlobject/main.py", line 1465, in selectBy
    conn = connection or cls._connection
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/lx310venv/lib/python3.10/site-packages/sqlobject/dbconnection.py", line 985, in __get__
    return self.getConnection()
  File "/media/gamedisk/PycharmProjects/FICSIT-Fred/lx310venv/lib/python3.10/site-packages/sqlobject/dbconnection.py", line 997, in getConnection
    raise AttributeError(
AttributeError: No connection has been defined for this thread or process. Did you mean: 'setConnection'?

Process finished with exit code 1
```
Platform: Linux Mint 20.2 Cinnamon 5.0.6
Python 3.10.0 (default, Oct  4 2021, 22:09:55) [GCC 9.3.0] on linux
SQLObject==3.9.1

seems related to #55 but that doesn't seem to have a workaround or fix

**Comment by phdru** [comment]
What is the code that leads to the exception?

**Comment by AstroFloof** [comment]
Unfortunately I think the issue was on my end... I put the code asking the DB for stuff to make class attributes, which is called before the master __init__() in which the connection is made.

**Comment by phdru** [comment]
If you can provide a small test case we can discuss if it's worth fixing in SQLObject code. If not please close the issue.

**Comment by AstroFloof** [comment]
No, it's my fault. Here's what I did to resolve the issue:
```py
# main.py
import submodule


class MainThing:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # ...
        self.setup_DB()
        submodule.ProblemChild.class_init()  # now that the DB is up, this can be called
        # ...
 ```
 ```py
 # submodule.py
import dbthingy


class ProblemChild(ProblemParent):

    integer: int = 0
    string: str = '>'

    def __init__(self):
        # since this gets called for object instancing, 
        # fetching from DB every time here would be inefficient
    
    @classmethod
    def class_init(cls):
        cls.integer = dbthingy.fetch_integer()
        cls.string = dbthingy.fetch_string()
```

**Comment by phdru** [comment]
Ok, thanks for sharing!

**Comment by AstroFloof** [comment]
Sorry for the waste of time lol
