### ISSUE TITLE
ForeignKey cascade=None not working in PostgreSQL

### ISSUE THREAD

**Issue by scyclops** [sqlobject/sqlobject#182]
The code below should reproduce the error with PostgreSQL.

```python

from sqlobject import SQLObject, ForeignKey

class Person(SQLObject):
    pass

class Item(SQLObject):
    owner = ForeignKey('Person', cascade=None)

Person.createTable(ifNotExists=True)
Item.createTable(ifNotExists=True)

john = Person()
john_id = john.id

item = Item(owner=john)

# now delete Person john which should succeed
Person.delete(john.id)
# but SQLObject throws the following IntegrityError:
#
# IntegrityError: update or delete on table "person" violates foreign key constraint "owner_id_exists" on table "item"
# DETAIL:  Key (id)=(1) is still referenced from table "item".
#
# And the IntegrityError happens because of the following constraint on the Item table:
# Foreign-key constraints:
#    "owner_id_exists" FOREIGN KEY (owner_id) REFERENCES person(id)
#
# If we drop the owner_id_exists constraint on the Item table, then everything works as intended.

assert item.ownerID == john_id

```

**Comment by phdru** [comment]
Thank you for reporting! Reproduced. With SQLite it works but with MySQL it's the same bug so it's not limited to Pstgres:
```
Traceback (most recent call last):
  File "./test-cascade.py", line 21, in <module>
    Person.delete(john.id)
  File "site-packages/sqlobject/main.py", line 1697, in delete
    obj.destroySelf()
  File "site-packages/sqlobject/main.py", line 1683, in destroySelf
    self._connection._SO_delete(self)
  File "site-packages/sqlobject/dbconnection.py", line 633, in _SO_delete
    self.sqlrepr(so.id)))
  File "site-packages/sqlobject/dbconnection.py", line 435, in query
    return self._runWithConnection(self._query, s)
  File "site-packages/sqlobject/dbconnection.py", line 342, in _runWithConnection
    val = meth(conn, *args)
  File "site-packages/sqlobject/dbconnection.py", line 431, in _query
    self._executeRetry(conn, c, s)
  File "site-packages/sqlobject/mysql/mysqlconnection.py", line 298, in _executeRetry
    raise dberrors.IntegrityError(msg)
sqlobject.dberrors.IntegrityError: Cannot delete or update a parent row: a foreign key constraint fails (`sqlobject_test`.`item`, CONSTRAINT `item_owner_id_exists` FOREIGN KEY (`owner_id`) REFERENCES `person` (`id`))
```

**Comment by phdru** [comment]
With `cascade=False` SQLObject generates stricter constraint, even SQLite obey it:
```sql
owner_id INT CONSTRAINT owner_id_exists REFERENCES person(id) ON DELETE RESTRICT
```

With `cascade=True` SQLObject generates commands to delete the referencing row:
```sql
owner_id INT CONSTRAINT owner_id_exists REFERENCES person(id) ON DELETE CASCADE
```

With `cascade='null'` SQLObject generates commands to nullify the referencing foreign key:
```sql
owner_id INT CONSTRAINT owner_id_exists REFERENCES person(id) ON DELETE SET NULL
```
So choose which behaviour you want from the backend.
